{
    "force_refresh": 0,
    "app_upgrade": 1,
    "source": "https://d.kstore.dev/download/14700/2025/yyxb/yyHD.json",
    "source_plus": "",
    "app_message": "程序默认启动HD专享路线无需设置，部分设备没有自动给予存储权限的无法使用，需要点击设置界面–自捣资源–权限 给予权限。本APP基于开源免费项目二次开发, 兼容tvbox标准接口, 仅供内部测试学习交流使用\n\n使用过程中若出现广告均为三方插入, 与本APP无关，请勿相信。",
    "jar_message": "感谢使用",
    "filter": [
        "王二小放牛娃.xyz",
        "神秘的哥哥们",
        "时光机",
        "虎斑",
        "小虎斑",
        "小虎版",
        "的口粮",
        "风月无边",
        "莺莺燕燕",
        "醉挽",
        "小满",
        "TimeFlix",
        "｜",
        "防失联",
        "关注",
        "【",
        "】",
        "┃ ",
        "小米接口群：665981772 "
    ],
    "prefix": "余影相绊HDTV",
    "prefix_wolong": "余影相绊HDTV",
    "title": "余影相绊HDTV",
    "jxUrl": "https://www.lintech.work/api/m3u8/parse?token=%s&url=%s",
    "danmuUrl": "",
    "notice": "https://www.lintech.work/static/config/notice.js",
    "parse_no_header": 0,
    "live": "",
    "upgrade": "https://gh.llkk.cc/https://raw.githubusercontent.com/bestpvp/uateCenter/refs/heads//main/",
    "source_backdoor_plus": "https://zyoutv.xyz/2025/yuying/yyHD.json",
    "source_backdoor": "https://zyoutv.xyz/2025/yuying/yyHD.json",
    "customization": 1
}
